language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sayerameshbabu/react-myapp -f Dockerfile.dev .
script:
  - docker run -e CI=true sayerameshbabu/docker-react npm run test -- --coverage