language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sayerameshbabu/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sayerameshbabu/docker-react npm run test -- --coverage
  - cat /etc/*release
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-1-540796733493"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY